### ISSUE TITLE
make colors adjustable / at least support a dark theme

### ISSUE THREAD

**Issue by ErikBrendel** [Chris2011/nb-codeoutline#22] opened 2016-01-04 17:46 UTC
I would really lov to have this feature in netbeans, but i'm using the dark metal theme with custom editor colors. The white / bright design of the code outline really isn't nice and you can't see anything

![screenshot](https://cloud.githubusercontent.com/assets/11018565/12096086/3e03422e-b313-11e5-8dac-262b7567a8fa.PNG)

Could you make color changing possible? Or maybe you could use the same color settings the code area already has?

Thanks :)
TMUKingston

**Comment by markiewb** [comment] 2016-01-04 19:25
Thank you for you interest, but it is not as easy as you might think. Closing as a duplicate of https://github.com/markiewb/nb-codeoutline/issues/8

**Closed as completed by markiewb** 2016-01-04 19:25 UTC
Labels: enhancement, invalid

**Comment by markiewb** [comment] 2016-01-04 23:07
BTW: Fixed in 1.3.0
