### ISSUE TITLE
Not works for me

### ISSUE THREAD

**Issue by Matvik** [Chris2011/nb-codeoutline#32] opened 2016-10-11 13:35 UTC
No outline appears
[http://prntscr.com/csi818](http://prntscr.com/csi818)

**Comment by Chris2011** [comment] 2016-10-14 08:29
It works for me neither. I think it is a problem of NetBeans 8.2. Same problem. No error, no code outline. @markiewb do you know the problem?

**Comment by markiewb** [comment] 2016-10-15 09:04
Yes, I found the problem. The UI structure has been changed. Will be fixed in 1.3.2. 

So far a duplicate of #31

**Closed as completed by markiewb** 2016-10-15 09:04 UTC
Labels: duplicate
