### ISSUE TITLE
Please add lines of flag labels on the ribbon

### ISSUE THREAD

**Issue by korenevskiy** [Chris2011/nb-codeoutline#43] opened 2022-10-25 22:54 UTC
Please add lines of flag labels on the ribbon. Programmers put check marks in front of the function or code editing of the place where all the work and debugging takes place. But the debugging position is not visible on the module ribbon, since the labels are not displayed. It is necessary to show the placemark placement positions, as line bright blue for a dark theme, and  as line dark blue for a light one.

**Comment by Chris2011** [comment] 2022-10-26 09:49
Isn't this the same as https://github.com/markiewb/nb-codeoutline/issues/42 ?

**Comment by korenevskiy** [comment] 2022-10-26 20:45
> Isn't this the same as #42 ?

You Right

**Comment by Chris2011** [comment] 2022-10-28 18:53
As mentioned, it is a duplicate of #42

**Closed as completed by Chris2011** 2022-10-28 18:53 UTC
